#-------------------------------
# General Site Settings

title: Losmontoya
description: Thinker // Designer // Podcaster
email: los@losmontoya.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Daps, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Logo Designer, Brand Designer, Identity Designer, UX/UI Designer'
  rel-author: 'https://plus.google.com/u/0/103733062833237319027/posts/p/pub'
  rel-publisher: 'https://plus.google.com/u/0/103733062833237319027/posts/p/pub'

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **I am a connoisseur of the mustache.** 
  UI/UX designer [by day](http://www.popmessage.com/) Brand & Identity designer [by night](https://dribbble.com/los?page=1). I'm also trying this [Podcast thing.](http://www.travandlos.com/)

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Bird's Eye, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: POP Messenger Case Study, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Rekha Chagarlamudi, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Logo Concepts, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Ship.io, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Makers Vine, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Cinder, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Code Course, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'travitar.jpg',
  name: 'Travis Neilson',
  title: 'Senior Product Designer, Tubular Labs',
  quote: '<p><strong>Los is great to work with.</strong> Not just because of his talent and insight, but because of the way he adapts to new problems like a true professional.</p>',
  logo: 'tubular.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Carlos was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}
  
  
#-------------------------------
# Contact Section
  
social:
- {icon: 'twitter', link: 'https://twitter.com/losmontoya_'}
- {icon: 'dribbble', link: 'https://dribbble.com/los'}
- {icon: 'facebook', link: 'https://www.facebook.com/carlos.a.montoya.75'}
- {icon: 'instagram', link: 'http://instagram.com/losmontoya'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/losmontoya'}

  
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
  
  
  
  
  
  